// <auto-generated />
using System;
using GlobalSolution_.NET.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GlobalSolution_.NET.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalSolution_.NET.Models.CoordenadasModel", b =>
                {
                    b.Property<int>("id_coordenadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_coordenadas");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_coordenadas"));

                    b.Property<double>("latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("latitude");

                    b.Property<double>("longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("longitude");

                    b.HasKey("id_coordenadas");

                    b.ToTable("Coordenadas");
                });

            modelBuilder.Entity("GlobalSolution_.NET.Models.DeteccaoModel", b =>
                {
                    b.Property<int>("id_deteccao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_deteccao");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_deteccao"));

                    b.Property<DateTime>("data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data");

                    b.Property<int>("id_coordenadas")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_coordenadas");

                    b.Property<int>("id_especie")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_especie");

                    b.HasKey("id_deteccao");

                    b.HasIndex("id_coordenadas");

                    b.HasIndex("id_especie");

                    b.ToTable("Deteccao");
                });

            modelBuilder.Entity("GlobalSolution_.NET.Models.EspecieModel", b =>
                {
                    b.Property<int>("id_especie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_especie");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_especie"));

                    b.Property<int?>("Tiposid_risco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("especie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("especie");

                    b.Property<int>("id_risco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_risco");

                    b.Property<string>("nome_comum")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_comum");

                    b.HasKey("id_especie");

                    b.HasIndex("Tiposid_risco");

                    b.ToTable("Especie");
                });

            modelBuilder.Entity("GlobalSolution_.NET.Models.TiporiscoModel", b =>
                {
                    b.Property<int>("id_risco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_risco");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_risco"));

                    b.Property<int>("categoria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("categoria");

                    b.HasKey("id_risco");

                    b.ToTable("Tipo_risco");
                });

            modelBuilder.Entity("GlobalSolution_.NET.Models.DeteccaoModel", b =>
                {
                    b.HasOne("GlobalSolution_.NET.Models.CoordenadasModel", "Coordenadas")
                        .WithMany("Deteccao")
                        .HasForeignKey("id_coordenadas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalSolution_.NET.Models.EspecieModel", "Especie")
                        .WithMany("Deteccao")
                        .HasForeignKey("id_especie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordenadas");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("GlobalSolution_.NET.Models.EspecieModel", b =>
                {
                    b.HasOne("GlobalSolution_.NET.Models.TiporiscoModel", "Tipos")
                        .WithMany("Especie")
                        .HasForeignKey("Tiposid_risco");

                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("GlobalSolution_.NET.Models.CoordenadasModel", b =>
                {
                    b.Navigation("Deteccao");
                });

            modelBuilder.Entity("GlobalSolution_.NET.Models.EspecieModel", b =>
                {
                    b.Navigation("Deteccao");
                });

            modelBuilder.Entity("GlobalSolution_.NET.Models.TiporiscoModel", b =>
                {
                    b.Navigation("Especie");
                });
#pragma warning restore 612, 618
        }
    }
}
